<a href="https://colab.research.google.com/github/TanyaKumari0204/Sabudh-Internship/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a=np.random.randint(0,100,size=10)
b=np.random.randint(-10,11,size=(3,4))
b_flat=b.reshape(-1)
a_copy=a.copy()
a_copy[0]=-1
c=a[::2]
print(a)
print(b)
print(b_flat)
print(a_copy)
print(c)

[90 39  1 88 19 31 32 84 14 23]
[[ 6 -6 -9  0]
 [-3  0  7 -6]
 [ 0  7 -4 -1]]
[ 6 -6 -9  0 -3  0  7 -6  0  7 -4 -1]
[-1 39  1 88 19 31 32 84 14 23]
[90  1 19 32 14]


In [ ]:
print(a[3])
print(b[-1])
print(b[:2,-2:])
b_row=b[1]
print(b_row)
b_col=b[:,0]
print(b_col)

88
[ 0  7 -4 -1]
[[-9  0]
 [ 7 -6]]
[-3  0  7 -6]
[ 6 -3  0]


In [ ]:
d=np.arange(1,11)
e=a+d
b_double=b*2
f=np.dot(b,b_double.T)
g=np.mean([a.mean(),b.mean(),b_double.mean()])
print(a)
print(b)
print(d)
print(b_double)
print(e)
print(f)
print(g)


[90 39  1 88 19 31 32 84 14 23]
[[ 6 -6 -9  0]
 [-3  0  7 -6]
 [ 0  7 -4 -1]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 12 -12 -18   0]
 [ -6   0  14 -12]
 [  0  14  -8  -2]]
[91 41  4 92 24 37 39 92 23 33]
[[ 306 -162  -12]
 [-162  188  -44]
 [ -12  -44  132]]
13.283333333333333


In [ ]:
a_sum=a.sum()
b_min=b.min()
b_double_max=b_double.max()
print(a_sum)
print(b_min)
print(b_double_max)

421
-9
14
